### ISSUE TITLE
Investigate dynamic waits

### ISSUE THREAD

**Issue by PhysicsJon** [dp2020-dev/Blazemeter_Shop_Automated_Tests#1]
https://github.com/dp2020-dev/Blazemeter_Shop_Automated_Tests/blob/3e00094b36be0b37fa2c7d61a5c8bcd0e0ff0ed1/cypress/e2e/E2EloginPurchases.cy.js#L24C12-L24C12

**Comment by dp2020-dev** [comment]
Addressed this by typing log in details, then verifying field completed with user detail via a .should(have.value).
