### ISSUE TITLE
Tidy up Contains methods

### ISSUE THREAD

**Issue by PhysicsJon** [dp2020-dev/Blazemeter_Shop_Automated_Tests#2]
https://github.com/dp2020-dev/Blazemeter_Shop_Automated_Tests/blob/3e00094b36be0b37fa2c7d61a5c8bcd0e0ff0ed1/cypress/e2e/E2EloginPurchases.cy.js#L30

This cold be simplified to ```cy.contains('.nav-link', this.userDetails.welcomeText);```

**Comment by dp2020-dev** [comment]
Good spot, change actioned in latest commit.
